<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>SportMatrix.Application</AssemblyName>
    <RootNamespace>SportMatrix.Application</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AutoMapper" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SportMatrix.Domain\SportMatrix.Domain.csproj" />
  </ItemGroup>

</Project>
